codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    patch:
      default:
        target: 100%
    project:
      default:
        target: 60%

ignore:
  - ".tox/**/*"
  - "release.py"
  - "setup.py"
  - "tests/**/*"
