name: functional-treatment-effects

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python==3.10
  - ipython
  - pip
  - jupyterlab

  # Computation
  - numpy
  - pandas

  # Plotting
  - matplotlib
  - plotly
  - python-kaleido

  # Workflow
  - pytask
  - pytask-latex

  # Testing and Linting
  - black
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda
  - pdbpp


  - pip:
    - git+https://github.com/timmens/fte.git
    - git+https://github.com/timmens/pytask-markdown.git
    - -e .
