name: functional-treatment-effects

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python==3.10
  - pip

  # Computation
  - numpy
  - pandas

  # Plotting
  - matplotlib
  - plotly
  - python-kaleido

  - pip:
    - git+https://github.com/timmens/fte.git
    - git+https://github.com/timmens/pytask-markdown.git
    - -e .
